services:

  rabbit:
    image: rabbitmq:4.1.0-beta.5-management
    container_name: rabbit
    ports:
      - "5672:5672" #Puerto de mensajería
      - "15672:15672" #Puerto/interfaz de administración
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: user